# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-06 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
